// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tickets.DL;

#nullable disable

namespace tickets.DL.Migrations
{
    [DbContext(typeof(context))]
    [Migration("20230501222647_kkk")]
    partial class kkk
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.Property<int>("DevelopersId")
                        .HasColumnType("int");

                    b.Property<int>("TicketsId")
                        .HasColumnType("int");

                    b.HasKey("DevelopersId", "TicketsId");

                    b.HasIndex("TicketsId");

                    b.ToTable("DeveloperTicket");
                });

            modelBuilder.Entity("tickets.DL.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ai"
                        },
                        new
                        {
                            Id = 2,
                            Name = "os"
                        },
                        new
                        {
                            Id = 3,
                            Name = "pd"
                        },
                        new
                        {
                            Id = 4,
                            Name = "sa"
                        },
                        new
                        {
                            Id = 5,
                            Name = "os"
                        });
                });

            modelBuilder.Entity("tickets.DL.Developer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("developers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "ali"
                        },
                        new
                        {
                            Id = 2,
                            Name = "ahmed"
                        },
                        new
                        {
                            Id = 3,
                            Name = "sara"
                        },
                        new
                        {
                            Id = 4,
                            Name = "aya"
                        },
                        new
                        {
                            Id = 5,
                            Name = "alyaa"
                        });
                });

            modelBuilder.Entity("tickets.DL.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 1,
                            Description = "ticket discription",
                            Title = "ticket title"
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 2,
                            Description = "ticket discription",
                            Title = "ticket title"
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Description = "ticket discription",
                            Title = "ticket title"
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 4,
                            Description = "ticket discription",
                            Title = "ticket title"
                        },
                        new
                        {
                            Id = 5,
                            DepartmentId = 5,
                            Description = "ticket discription",
                            Title = "ticket title"
                        });
                });

            modelBuilder.Entity("DeveloperTicket", b =>
                {
                    b.HasOne("tickets.DL.Developer", null)
                        .WithMany()
                        .HasForeignKey("DevelopersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("tickets.DL.Ticket", null)
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("tickets.DL.Ticket", b =>
                {
                    b.HasOne("tickets.DL.Department", "Department")
                        .WithMany("tickets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("tickets.DL.Department", b =>
                {
                    b.Navigation("tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
